### ISSUE TITLE
plant_isce3_geocode.py  AttributeError: 'isce3.ext.isce3.geocode.GeocodeCFloat32' object has no attribute 'dem_block_margin

### ISSUE THREAD

**Issue by Narayana-Rao** [isce-framework/plant-isce3#1]
I am trying to install and use [plant-isce3](https://github.com/isce-framework/plant-isce3). Therefore, I have installed latest isce3 ('0.8.0-dev+04b17713'). The following test are failed (Ubuntu 20.04; GDAL 3.0.4; Python 3.8.5) 
[LastTest.log](https://github.com/isce-framework/isce3/files/9340091/LastTest.log)

```
140:test.python.pkg.isce3.ionosphere.ionosphere
153:test.python.pkg.nisar.workflows.stage_dem
162:test.python.pkg.nisar.workflows.ionosphere
```

Still I have installed [plant](https://anaconda.org/plant/plant), [plant-isce3](https://github.com/isce-framework/plant-isce3). However, while running ``plant_isce3_geocode.py``, I have encountered the following error ([plant_isce3.log](https://github.com/isce-framework/isce3/files/9340092/plant_isce3.log)). Could anyone please suggest any fix for this. 

```
AttributeError: 'isce3.ext.isce3.geocode.GeocodeCFloat32' object has no attribute 'dem_block_margin'
```

**Comment by gshiroma** [comment]
Hi @Narayana-Rao , thank you for reporting this issue. I'll debug it and fix the code soon (probably over the weekend). Will keep you posted.

**Comment by gshiroma** [comment]
Hi @Narayana-Rao, thank you again for reporting this issue. I just pushed a [commit](https://github.com/isce-framework/plant-isce3/commit/19ce9e6cc70212213be7b93e76c855c39e312d13) that fixes the `dem_block_margin` attribute error. Please try again.

**Comment by Narayana-Rao** [comment]
Thank you, @gshiroma, for the fix.

Now, I am facing the following issue. Could you please help. 

```PLAnT 0.0.??dev - plant_isce3_geocode.py "/Users/mirsl1-mac/NRB_UMass/ASAR/GCOV/ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3_MD.h5" --dem "/Users/mirsl1-mac/NRB_UMass/ASAR/GCOV/dem/demLat_N41_N43_Lon_W073_W070.dem.wgs84.vrt" -f --area-proj-gamma-naught --sm "30" --cov "C3"
input file: /Users/mirsl1-mac/NRB_UMass/ASAR/GCOV/ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3_MD.h5
lat step: 0.0002694945852359 (approx. 30.0m)
lon step: 0.0002694945852359 
    WARNING invalid data type NoneType (GDAL). Converting output to Float32..
0...10...20...30...40...50...60...70...80...90...100 - done.
    file saved: temp_1664499351.73362296.vrt (GDAL:VRT)
x0_orig: nan
y0_orig: nan
self.step_lon: 0.0002694945852358564
self.step_lat: 0.0002694945852358564
lon_size: -9999
lat_size: -9999
epsg: 4326
geo2rdr threshold: 1e-08
geo2rdr num iter: 100
interp method: biquintic
self.lon_arr: [-72.27462827120607, -72.03801202536899]
self.lat_arr: [42.314253599035624, 42.740863527463986]
self.lon_size: 878
self.lat_size: 1583
self.step_lon: 0.0002694945852358564
self.step_lat: 0.0002694945852358564
Segmentation fault: 11```

**Comment by gshiroma** [comment]
Segmentation fault is usually related to memory issues. `plant_isce3_geocode.py` has a mode that requires less memory (at the cost of a longer run time). Please try add the following argument to your command: `--memory-mode blocks-geogrid-and-radargrid`.

**Comment by Narayana-Rao** [comment]
Thank you @gshiroma, but the issue is still there. Am I missing something?

```
PLAnT 0.0.??dev - plant_isce3_geocode.py "/Users/mirsl1-mac/NRB_UMass/ASAR/GCOV/ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3_MD.h5" --dem "/Users/mirsl1-mac/NRB_UMass/ASAR/GCOV/dem/demLat_N41_N43_Lon_W073_W070.dem.wgs84.vrt" -f --area-proj-gamma-naught --sm "30" --cov "C3" --memory-mode "blocks-geogrid-and-radargrid"
input file: /Users/mirsl1-mac/NRB_UMass/ASAR/GCOV/ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3_MD.h5
lat step: 0.0002694945852359 (approx. 30.0m)
lon step: 0.0002694945852359 
    WARNING invalid data type NoneType (GDAL). Converting output to Float32..
0...10...20...30...40...50...60...70...80...90...100 - done.
    file saved: temp_1664566681.295987702.vrt (GDAL:VRT)
x0_orig: nan
y0_orig: nan
self.step_lon: 0.0002694945852358564
self.step_lat: 0.0002694945852358564
lon_size: -9999
lat_size: -9999
epsg: 4326
geo2rdr threshold: 1e-08
geo2rdr num iter: 100
interp method: biquintic
self.lon_arr: [-72.27462827120607, -72.03801202536899]
self.lat_arr: [42.314253599035624, 42.740863527463986]
self.lon_size: 878
self.lat_size: 1583
self.step_lon: 0.0002694945852358564
self.step_lat: 0.0002694945852358564
Segmentation fault: 11

```

**Comment by gshiroma** [comment]
Hi @Narayana-Rao , the initial values `x0_orig`, `y0_orig`, `lon_size`, and `lat_size` are invalid but the final values seem to be correct. I think the segmentation fault problem is related to lack of memory to process the entire dataset. You can also process subsets of this dataset, for example, you can use the argument `--bbox  LAT_MIN LAT_MAX LON_MIN LON_MAX` to limit the extents (bounding box) of the output imagery. Please try to process a small subset of your dataset and see if this works. Thank you.

**Comment by gshiroma** [comment]
In addition to changing the bbox, you can also use `--step STEP` to change the step size. Please keep in mind that for your dataset, the step size is given in degrees (not meters).

**Comment by Narayana-Rao** [comment]
Thank you, @gshiroma. I have tried using ```--bbox``` and ```--step```  such a way that it creates a ```~51x51``` pixel subset. However, I am facing the same issue

```
PLAnT 0.0.??dev - plant_isce3_geocode.py "/Users/mirsl1-mac/NRB_UMass/ASAR/GCOV/ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3_MD.h5" --dem "/Users/mirsl1-mac/NRB_UMass/ASAR/GCOV/dem/demLat_N41_N43_Lon_W073_W070.dem.wgs84.vrt" -f --area-proj-gamma-naught --sm "30" --cov "C3" --memory-mode "blocks-geogrid-and-radargrid" --bbox "42.33" "42.34" -72.21 -72.20 --step=0.0002
input file: /Users/mirsl1-mac/NRB_UMass/ASAR/GCOV/ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3_MD.h5
coordinates from bbox
boundaries (outer edges):
lat: 42.3298999999999950, 42.3401000000000067
lon: -72.2100999999999971, -72.1998999999999995
center lat: 42.3350000000000009
center lon: -72.2049999999999983
lat step: 0.0002000000000000 (approx. 22.3m)
lon step: 0.0002000000000000 (approx. 16.5m at lat=42)
lat size [deg]: 0.0102000000000000 (approx. 1.135km)
lon size [deg]: 0.0102000000000000 (approx. 0.839km at lat=42)
    WARNING invalid data type NoneType (GDAL). Converting output to Float32..
0...10...20...30...40...50...60...70...80...90...100 - done.
    file saved: temp_1665007162.8926232430.vrt (GDAL:VRT)
x0_orig: -72.2101
y0_orig: 42.34010000000001
self.step_lon: 0.0002
self.step_lat: 0.0002
lon_size: 51
lat_size: 51
epsg: 4326
geo2rdr threshold: 1e-08
geo2rdr num iter: 100
interp method: biquintic
self.lon_arr: [-72.21, -72.1998]
self.lat_arr: [42.329800000000006, 42.34]
self.lon_size: 51
self.lat_size: 51
self.step_lon: 0.0002
self.step_lat: 0.0002
Segmentation fault: 11
```

**Comment by gshiroma** [comment]
I'm sorry for that @Narayana-Rao . Is this dataset public? Or could you send it to me via email? I can try to debug it for you.

**Comment by Narayana-Rao** [comment]
Thank you very much, @gshiroma, for your reply. Yes, the dataset is publicly available at following URL
[https://uavsar.jpl.nasa.gov/cgi-bin/asar.py?jobName=harvar_18523_A2107_010_210714_V1.3.B](https://uavsar.jpl.nasa.gov/cgi-bin/asar.py?jobName=harvar_18523_A2107_010_210714_V1.3.B)

**Comment by gshiroma** [comment]
> Thank you very much, @gshiroma, for the reply. Yes, the dataset is publicly available at the following URL https://uavsar.jpl.nasa.gov/cgi-bin/asar.py?jobName=harvar_18523_A2107_010_210714_V1.3.B

Thank you, @Narayana-Rao . The process ran successfully here to completion. I tested it with isce3 from conda (version 0.8.0) and the plant-isce3 command that I used is the following:
```
 plant_isce3_geocode.py "ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5" --dem "/home/shiroma/dat/nisar-dem-copernicus-2/EPSG4326.vrt" -o "l2_gcov.bin" -f
```
Full log:
```
plant_isce3_geocode.py ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5 --dem ~/dat/nisar-dem-copernicus-2/EPSG4326.vrt -o l2_gcov.bin -f
SYSTEM elapsed time: 233ms
(43ms +43ms)          PLAnT 0.1.80dev - plant_isce3_geocode.py "ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5" --dem "/home/shiroma/dat/nisar-dem-copernicus-2/EPSG4326.vrt" -o "l2_gcov.bin" -f
(44ms +<0ms)          input file: ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5
(104ms +60ms)             WARNING invalid data type NoneType (GDAL). Converting output to Float32..
0...10...20...30...40...50...60...70...80...90...100 - done.
(128ms +23ms)             file saved: temp_1665265992.592127327.vrt (GDAL:VRT)
(152ms +24ms)         x0_orig: nan
(152ms +<0ms)         y0_orig: nan
(153ms +<0ms)         self.step_lon: nan
(153ms +<0ms)         self.step_lat: nan
(154ms +<0ms)         lon_size: -9999
(154ms +<0ms)         lat_size: -9999
(154ms +<0ms)         epsg: 4326
(155ms +<0ms)         geo2rdr threshold: 1e-08
(156ms +<0ms)         geo2rdr num iter: 100
(157ms +<0ms)         interp method: biquintic
(159ms +2ms)          self.lon_arr: [-72.2714108043405, -72.03807747100716]
(160ms +<0ms)         self.lat_arr: [42.34141494142324, 42.740859385867715]
(160ms +<0ms)         self.lon_size: 840
(161ms +<0ms)         self.lat_size: 1438
(162ms +<0ms)         self.step_lon: 0.0002777777777778
(162ms +<0ms)         self.step_lat: 0.0002777777777778
(165ms +2ms)          flag_rtc_bilinear_distribution: False
(166ms +<0ms)         flag_rtc_area_proj: False
(167ms +<0ms)         flag_geocode_interp: False
(167ms +<0ms)         flag_geocode_area_proj: False
(168ms +<0ms)         geocode kwargs: {'rtc_algorithm': <RtcAlgorithm.RTC_AREA_PROJECTION: 1>, 'output_terrain_radiometry': <RtcOutputTerrainRadiometry.GAMMA_NAUGHT: 1>, 'input_terrain_radiometry': <RtcInputTerrainRadiometry.BETA_NAUGHT: 0>, 'radargrid_nlooks': 1, 'output_mode': <GeocodeOutputMode.AREA_PROJECTION: 1>, 'flag_apply_rtc': False}
journal:
 -- nbands: 4
 -- full covariance: false
 -- nbands: 4
 -- radar grid width: 3558, length: 37587
 -- geogrid upsampling: 1
 -- DEM EPSG: 4326
journal: output EPSG: 4326
journal:
 -- reproject DEM (0: false, 1: true): 0
 -- reading input raster band: 1
journal: reading input raster band: 2
journal: reading input raster band: 3
journal: reading input raster band: 4
journal:
 -- array length: 1438
 -- array width: 840
 -- number of available thread(s): 32
 -- number of block(s):  1 x 1 (Y x X) = 1
 -- block length: 1438
 -- block width: 840
 -- block size: 19MB (4 bands)
journal:
 -- nblocks X: 1
 -- block size X: 840
 -- block size X (with upsampling): 840
 -- nblocks Y: 1
 -- block size Y: 1438
 -- block size Y (with upsampling): 1438
 -- starting geocoding
geocode progress: 100%
journal: elapsed time (GEO-AP) [s]: 20.902
removing temporary file(s)...
    temp_1665265992.592127327.vrt
(21s299ms +21s130ms)  output file(s):
(21s299ms +<0ms)          l2_gcov.bin
elapsed time: 21s 300ms
log: _plant_log/plant_isce3_geocode_2022_10_08_14_53_12.log
```

**Comment by gshiroma** [comment]
I think I found the issue. Try adding a name for the output file: `-o l2_gcov.bin` . Please, also remove `--memory-mode "blocks-geogrid-and-radargrid"`.

**Comment by Narayana-Rao** [comment]
Thank you very much, @gshiroma, this has fixed the issue. However, I have noticed the following in the output (C4 matrix) :
 *  The C4 elements in the output C3 folder do not have any georeference information ( ```map info```  and  ```coordinate system string``` tags in ```.hdr``` file), but the output ```l2_gcov.bin``` contains it.
 *  It seems the band order in ```l2_gcov.bin``` in reverse i.e. ```band-1=C44.bin, band2=C33.bin, band3=C22.bin and band4=C11.bin```. 

Please verify these.

**Comment by gshiroma** [comment]
Thank you, @Narayana-Rao , for the feedback. The polarizations are in reverse order because the `listOfPolarizations` is inverted in the input RSLC file:
```
plant_display.py   HDF5:ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5://science/LSAR/RSLC/swaths/frequencyA/listOfPolarizations --print
SYSTEM elapsed time: <0ms
(14ms +14ms)          PLAnT 0.1.80dev - plant_display.py "HDF5:ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5://science/LSAR/RSLC/swaths/frequencyA/listOfPolarizations" --print
(124ms +109ms)        input 1: HDF5:ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5://science/LSAR/RSLC/swaths/frequencyA/listOfPolarizations
(125ms +<0ms)             arguments: HDF5:ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5://science/LSAR/RSLC/swaths/frequencyA/listOfPolarizations --print
(126ms +<0ms)             name: ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5
(126ms +<0ms)             format: HDF5
(127ms +<0ms)             dtype: dtype[bytes_]
(128ms +<0ms)             width: 4
(129ms +<0ms)             length: 1
(131ms +2ms)              opening: ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5 (HDF5: science/LSAR/RSLC/swaths/frequencyA/listOfPolarizations)
(143ms +11ms)         input 1:
(144ms +<0ms)             color: #7293cb
(144ms +<0ms)             linecolor: black
(145ms +<0ms)             linestyle: solid
(146ms +<0ms)             linewidth: 2
(147ms +<0ms)             linecolor (stats): black
(147ms +<0ms)             linewidth (stats): 2
(148ms +<0ms)         print data options:
(149ms +<0ms)             point #       line    column  ASAR_L_JOINT_FP_ID18523_LINE10_RUN01_140721_LEVEL1_RSLC_V1.3.B.h5
(150ms +<0ms)             1             1       1       VV
(150ms +<0ms)             2             1       2       VH
(151ms +<0ms)             3             1       3       HV
(152ms +<0ms)             4             1       4       HH
```

Notice that the polarization order of the input file is VV, VH, HV, and HH.

You are right, the output covariance matrix does not have geoinformation. To copy the geoinformation to one of the outputs you can use the following command:

```
plant_util.py   C3/C11.bin l2_gcov.bin   --copy-geotransform  -o C3/C11_with_geoinformation.bin
```

Notice that --copy-geotransform *"'Import geo-information from second image to the first, saving results into the output file"*.
